name: build
on:
  workflow_dispatch:
  workflow_run:
    workflows: [test]
    types: [completed]
permissions:
  actions: write
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CACHENAME: ${{ runner.os }}-go-main-
jobs:
  build:
    uses: ./.github/workflows/reusing_build.yml
