name: build
on:
  workflow_dispatch:
  workflow_run:
    workflows: [test]
    types: [completed]
permissions:
  actions: write
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    uses: tkmsaaaam/manage-slack/.github/workflows/reusing_build.yml@main
    with:
      FILE_NAME: main
