name: ManageActions
on:
  schedule:
    - cron: '12 12 1 * *'
  workflow_dispatch:
permissions:
  actions: write
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout self repo
        uses: actions/checkout@v3
      - name: disable self action
        run: gh workflow disable "ManageActions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: enable self action
        run: gh workflow enable "ManageActions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: disable target action
        run: gh workflow disable "CountCommits"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: enable target action
        run: gh workflow enable "CountCommits"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
