name: ManageActions
on:
  schedule:
    - cron: '12 12 1 * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/manage_actions.yml"
permissions:
  actions: write
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: Re-enable actions
        uses: tkmsaaaam/manage-slack/blob/main/.github/workflows/manage_action.yml@main
