name: Reusing
on:
  workflow_call:
permissions: {}
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/${{ github.event.repository.name }}
          key: ${{ runner.os }}-go-main-
          restore-keys: ${{ runner.os }}-go-main-
      - name: Execute
        run: ${{ github.workspace }}/${{ github.event.repository.name }}
