name: CountCommits
on:
  schedule:
    - cron: '37 11 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    types: [completed]
env:
  USER_NAME: ${{ secrets.USER_NAME }}
  TOKEN_FOR_BOT: ${{ secrets.TOKEN_FOR_BOT }}
  CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions: {}
jobs:
  script:
    uses: ./.github/workflows/reusing_execute.yml
