name: CountCommits

on:
  schedule:
    - cron: '37 11 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go
      - name: check out
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run script
        run : go run main.go ${{ secrets.USER_NAME }} ${{ secrets.TOKEN_FOR_BOT }} ${{ secrets.CHANNEL_ID }} ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 1
