name: CountCommits
on:
  schedule:
    - cron: '37 11 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    types: [completed]
permissions: {}
jobs:
  script:
    uses: tkmsaaaam/manage-slack/.github/workflows/reusing_execute.yml@main
    with:
      cacheName: main
      fileName: main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_USER_NAME: ${{ secrets.GH_USER_NAME }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
