name: CountCommits
on:
  schedule:
    - cron: '37 11 * * *'
  workflow_dispatch:
permissions: {}
jobs:
  script:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: count-commits-js
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}
          key: ${{ runner.os }}-go-${{ github.sha }}
      - name: Execute
        run: ~/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/${{ env.REPO_NAME }} ${{ secrets.USER_NAME }} ${{ secrets.TOKEN_FOR_BOT }} ${{ secrets.CHANNEL_ID }} ${{ secrets.GITHUB_TOKEN }}
